Compare develop to main
LBHackney-IT/repairs-hub-frontend pull request #251
Opened 2021-06-18 14:55 UTC by EGiataganas

2021-06-18 15:42 UTC, NeilvB requested changes

2021-06-18 15:42 UTC, NeilvB commented on cypress/integration/search/search-for-property-or-work-order.spec.js
> +        it.only('checks the heading', () => {
Please can we remove this as it's causing the other tests to be skipped.

2021-06-21 12:32 UTC, benbaumann95 approved these changes

2021-06-21 12:34 UTC, NeilvB approved these changes

2021-06-21 12:42 UTC, merged