Show warning text when current day is above work order's target date
LBHackney-IT/repairs-hub-frontend pull request #298
Opened 2021-07-21 13:11 UTC by EGiataganas

### Description of change

Show warning text when current day is above work order's target date and add a link raise a new repair

### Story Link

https://www.pivotaltracker.com/story/show/178928505

### Screenshot

![Screenshot 2021-07-21 at 14 07 34](https://user-images.githubusercontent.com/7561969/126493800-4667d6f5-72b9-4b84-a6d7-33813bde1a0f.jpg)
![Screenshot 2021-07-21 at 14 08 22](https://user-images.githubusercontent.com/7561969/126493808-896bf7d2-591f-4eb1-800f-d4d0b09427bd.jpg)

2021-07-21 16:00 UTC, NeilvB requested changes
Requesting that we take another look at the target date logic and also consider making it a method on `WorkOrder` (the new model).

2021-07-22 10:57 UTC, EGiataganas commented on cypress/integration/work-order/authorisation.spec.js
> +    })
We need this as I've added the test that it will include the `Raise a new work order`

2021-07-22 12:46 UTC, NeilvB commented on src/models/work-order.test.js
> +    it('returns true when the current time is past the appointment start time', () => {
Thanks for spotting and fixing this

2021-07-22 12:47 UTC, NeilvB approved these changes

2021-07-22 12:49 UTC, EGiataganas commented on src/models/work-order.test.js
> +    it('returns true when the current time is past the appointment start time', () => {
No worries!

2021-07-22 12:49 UTC, merged