Refactor raise form: push some options state up into parent
LBHackney-IT/repairs-hub-frontend pull request #678
Opened 2022-05-06 13:09 UTC by NeilvB

Required because there will soon be another form that is conditionally shown in this view.

To keep the available options for contractors, budget codes and sor codes when the user switches between forms, we need to lift that state up into the view. Otherwise the user would return to a raise form with no ability to change existing inputs.

2022-05-09 11:29 UTC, siapankina requested changes
Looks great! 
Happy to approve after comments are addressed

2022-05-09 11:29 UTC, siapankina commented on src/pages/api/[...path].test.js
> +        describe.only(`requesting the ${url} endpoint`, () => {
this can be removed :)

2022-05-09 11:29 UTC, siapankina commented on src/pages/api/[...path].test.js
> +        // 'api/workOrders/01234567/notes',
Probably this needs to be uncommented?

2022-05-16 10:41 UTC, NeilvB commented
Thanks @siapankina - I've removed those comments and spec restriction now. Please can you approve?

2022-05-18 08:31 UTC, siapankina approved these changes

2022-05-18 10:48 UTC, merged